### Data Cleaning

In [117]:
# importing the required libraries  
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [118]:
# reading the dataset 
df = pd.read_csv('..\\datasets\\job_salary_prediction_dataset.csv')
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

#### Statistical summary of the dataset:
---

In [119]:
print("Description of the dataset (numeric):")
pd.set_option('display.float_format', '{:,.2f}'.format)
print(df.describe())

Description of the dataset (numeric):
       experience_years  skills_count  certifications     salary
count        250,000.00    250,000.00      250,000.00 250,000.00
mean              10.01         10.00            2.49 145,718.08
std                6.06          5.48            1.71  37,407.95
min                0.00          1.00            0.00  31,867.00
25%                5.00          5.00            1.00 119,358.00
50%               10.00         10.00            2.00 143,453.00
75%               15.00         15.00            4.00 169,492.00
max               20.00         19.00            5.00 333,046.00

In [120]:
print("Description of the dataset (categorical):")
pd.set_option('display.float_format', '{:,.2f}'.format)
df.describe(include= str)

Description of the dataset (categorical):

,job_title,education_level,industry,company_size,location,remote_work
count,250000,250000,250000,250000,250000,250000
unique,12,5,10,5,10,3
top,Backend Developer,Master,Finance,Large,Australia,No
freq,21125,50352,25393,50254,25258,83621

In [121]:
print(df['job_title'].value_counts(),'\n')
print(df['education_level'].value_counts(),'\n')
print(df['company_size'].value_counts(),'\n')
print(df['location'].value_counts(),'\n')
print(df['industry'].value_counts(),'\n')

job_title
Backend Developer            21125
Cybersecurity Analyst        20959
Product Manager              20950
AI Engineer                  20945
Data Scientist               20890
DevOps Engineer              20889
Software Engineer            20876
Data Analyst                 20722
Cloud Engineer               20686
Machine Learning Engineer    20677
Business Analyst             20648
Frontend Developer           20633
Name: count, dtype: int64

education_level
Master         50352
High School    50065
Bachelor       49950
PhD            49857
Diploma        49776
Name: count, dtype: int64

company_size
Large         50254
Small         50235
Medium        50027
Enterprise    49875
Startup       49609
Name: count, dtype: int64

location
Australia      25258
Canada         25165
Sweden         25100
Remote         25065
Singapore      25035
USA            24931
UK             24927
India          24895
Netherlands    24861
Germany        24763
Name: count, dtype: int64

industry
Finance          25393
Consulting       25258
Media            25034
Manufacturing    25024
Technology       24903
Government       24901
Healthcare       24898
Education        24889
Telecom          24859
Retail           24841
Name: count, dtype: int64

In [122]:
print(df["remote_work"].value_counts())
print(df["certifications"].describe())
print(df["experience_years"].describe())

remote_work
No        83621
Hybrid    83476
Yes       82903
Name: count, dtype: int64
count   250,000.00
mean          2.49
std           1.71
min           0.00
25%           1.00
50%           2.00
75%           4.00
max           5.00
Name: certifications, dtype: float64
count   250,000.00
mean         10.01
std           6.06
min           0.00
25%           5.00
50%          10.00
75%          15.00
max          20.00
Name: experience_years, dtype: float64

In [123]:
print("\nDataset information:")
print(df.info())

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  str
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  str
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  str
 5   company_size      250000 non-null  str
 6   location          250000 non-null  str
 7   remote_work       250000 non-null  str
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), str(6)
memory usage: 19.1 MB
None

In [124]:
print("\nNumber of missing values in each column:")
print(df.isnull().sum())

Number of missing values in each column:
job_title           0
experience_years    0
education_level     0
skills_count        0
industry            0
company_size        0
location            0
remote_work         0
certifications      0
salary              0
dtype: int64

In [125]:
# checking the duplicates rows
print(df.duplicated().sum())

0

---

 for model training the data is cleaned but to handle those categorical value is necessary for linear regression model 
 so those data must be scaled, and encoded for the model training

In [126]:
df.groupby("company_size")["salary"].agg(["mean", "median", "count"])

                   mean     median  count
company_size
Enterprise   169,616.40 168,958.00  49875
Large        155,711.11 154,981.00  50254
Medium       141,537.54 140,861.00  50027
Small        134,356.86 134,001.00  50235
Startup      127,289.01 126,660.00  49609

In [127]:
# one-hot encoding operation on categorical data
df_clean = pd.get_dummies(
    df,columns=["job_title","industry","location",'remote_work'],drop_first=True, dtype=int
)

# Ordinal Encoding operation on categorical data  
education_map = {
    "High School": 0,
    "Diploma": 1,
    "Bachelor": 2,
    "Master": 3,
    "PhD": 4
}

company_map = {
    "Startup": 0,
    "Small": 1,
    "Medium": 2,
    "Large": 3,
    "Enterprise": 4
}

df_clean["education_level"] = df_clean["education_level"].map(education_map)
df_clean["company_size"] = df_clean["company_size"].map(company_map)

In [128]:
pd.set_option('display.max_columns', None)
df_clean.head()

,experience_years,education_level,skills_count,company_size,certifications,salary,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,job_title_Cybersecurity Analyst,job_title_Data Analyst,job_title_Data Scientist,job_title_DevOps Engineer,job_title_Frontend Developer,job_title_Machine Learning Engineer,job_title_Product Manager,job_title_Software Engineer,industry_Education,industry_Finance,industry_Government,industry_Healthcare,industry_Manufacturing,industry_Media,industry_Retail,industry_Technology,industry_Telecom,location_Canada,location_Germany,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_No,remote_work_Yes
0,10,2,2,2,2,109413,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
1,5,2,17,1,0,93764,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0
2,18,4,4,2,1,148123,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0
3,19,4,13,2,0,189123,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1
4,15,2,7,3,0,165069,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1

In [129]:
print(df_clean.select_dtypes(include="object").columns)

Index([], dtype='str')

In [130]:
print(df_clean.dtypes)

experience_years                       int64
education_level                        int64
skills_count                           int64
company_size                           int64
certifications                         int64
salary                                 int64
job_title_Backend Developer            int64
job_title_Business Analyst             int64
job_title_Cloud Engineer               int64
job_title_Cybersecurity Analyst        int64
job_title_Data Analyst                 int64
job_title_Data Scientist               int64
job_title_DevOps Engineer              int64
job_title_Frontend Developer           int64
job_title_Machine Learning Engineer    int64
job_title_Product Manager              int64
job_title_Software Engineer            int64
industry_Education                     int64
industry_Finance                       int64
industry_Government                    int64
industry_Healthcare                    int64
industry_Manufacturing                 int64
industry_Media                         int64
industry_Retail                        int64
industry_Technology                    int64
industry_Telecom                       int64
location_Canada                        int64
location_Germany                       int64
location_India                         int64
location_Netherlands                   int64
location_Remote                        int64
location_Singapore                     int64
location_Sweden                        int64
location_UK                            int64
location_USA                           int64
remote_work_No                         int64
remote_work_Yes                        int64
dtype: object

In [ ]:
df_clean.insert(6, 'log-salary',value= np.log1p(df['salary']))

In [132]:
df_clean.head()

,experience_years,education_level,skills_count,company_size,certifications,salary,log-salary,job_title_Backend Developer,job_title_Business Analyst,job_title_Cloud Engineer,job_title_Cybersecurity Analyst,job_title_Data Analyst,job_title_Data Scientist,job_title_DevOps Engineer,job_title_Frontend Developer,job_title_Machine Learning Engineer,job_title_Product Manager,job_title_Software Engineer,industry_Education,industry_Finance,industry_Government,industry_Healthcare,industry_Manufacturing,industry_Media,industry_Retail,industry_Technology,industry_Telecom,location_Canada,location_Germany,location_India,location_Netherlands,location_Remote,location_Singapore,location_Sweden,location_UK,location_USA,remote_work_No,remote_work_Yes
0,10,2,2,2,2,109413,11.60,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
1,5,2,17,1,0,93764,11.45,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0
2,18,4,4,2,1,148123,11.91,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0
3,19,4,13,2,0,189123,12.15,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1
4,15,2,7,3,0,165069,12.01,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1

In [133]:
df_clean.to_csv('..\\datasets\\dataset-for-model.csv', index= False)